name: Test HCT Cohort Definition

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-hct-cohort:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: "4.4.1"
        use-public-rspm: true
        
    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('DESCRIPTION') }}
        restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libcurl4-openssl-dev \
          libssl-dev \
          libxml2-dev \
          libfontconfig1-dev \
          libfreetype6-dev \
          libpng-dev \
          libtiff5-dev \
          libjpeg-dev \
          libharfbuzz-dev \
          libfribidi-dev
    
    - name: Install R dependencies
      run: |
        install.packages(c("remotes", "testthat"))
        # Install cohortTdd package
        remotes::install_github("bill-baumgartner/cohortTdd")
        # Install any additional dependencies
        if (file.exists("DESCRIPTION")) {
          remotes::install_deps(dependencies = TRUE)
        }
      shell: Rscript {0}
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Run HCT cohort validation tests
      run: |
        devtools::test()
      shell: Rscript {0}
    
    
    - name: Upload test results on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-results
        path: |
          tests/testthat/
          *.log