name: Test HCT Cohort Definition

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-hct-cohort:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: "4.4.1"
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libfontconfig1-dev
    
    - name: Install R dependencies
      run: |
        install.packages(c("remotes", "devtools", "testthat"))
        # Install cohortTdd package
        remotes::install_github("your-org/cohortTdd")
        # Install any additional dependencies
        if (file.exists("DESCRIPTION")) {
          remotes::install_deps(dependencies = TRUE)
        }
      shell: Rscript {0}
    
    - name: Run HCT cohort validation tests
      run: |
        devtools::test()
      shell: Rscript {0}
    
    - name: Run direct validation (alternative)
      run: |
        library(cohortTdd)
        results <- validate_my_cohort(
          patients_file = "data/hct_patients.xlsx",
          cohort_file = "cohorts/hct_cohort.json"
        )
        if (results$failed_tests > 0) {
          stop("HCT cohort validation failed")
        }
        cat("✅ HCT cohort validation passed!\n")
      shell: Rscript {0}
    
    - name: Upload test results on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-results
        path: |
          tests/testthat/
          *.log